############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "About"
url = "about/"
weight = 5

# footer menu
[[footer]]
name = "Legal"
url = "/legal"
weight = 1

[[footer]]
name = "Sitemap"
url = "/sitemap.xml"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy"
weight = 3

[[footer]]
name = "Terms of Service"
url = "/terms-of-service"
weight = 4
