backend:
  name: git-gateway
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: pages
    label: Pages
    files: 
      - name: home
        label: Home
        file: content/english/_index.md
        fields:
          - label: Hero Slider
            name: slider
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - label: Slides
                name: slider_item
                widget: list
                fields:
                  - { label: "Image", name: "bg_image", widget: "image" }
                  - { label: "Subtitle", name: "subtitle", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
                  - { label: "Pagination Icon", name: "pagination_icon", widget: "string" }
                  - { label: "Pagination Name", name: "pagination_name", widget: "string" }
                  - { label: "White Text", name: "textWhite", widget: "boolean" }
                  - label: "Button"
                    name: "button"
                    widget: object
                    fields:
                      - { label: "Enable", name: "enable", widget: "boolean" }
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Link", name: "link", widget: "string" }
          - label: Client Logos
            name: clients_logo_slider
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - label: Logos
                name: client_logos
                widget: list
                fields:
                  - { label: "Image", name: "logo", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
          - label: Services
            name: service
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: About
            name: about
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "text" }
              - Label: Bulletpoints
                name: bullet_point
                widget: list
              - label: "Button"
                name: button
                fields:
                  - { label: "Enable", name: "enable", widget: "boolean" }
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
          - label: FAQ
            name: faq
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: Questions
                name: entries
                widget: list
                fields:
                  - { label: "Question", name: "question", widget: "string" }
                  - { label: "Answer", name: "answer", widget: "text" }
          - label: Call to Action
            name: call_to_action
            widget: object
            fields:
              - { label: "Enable", name: "enable", widget: "boolean" }
              - { label: "Title", name: "title", widget: "string" }
      - name: about
        label: About
        file: content/english/about.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: CEO
            name: ceo
            widget: object
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Designation", name: "designation", widget: "string" }
              - { label: "Image", name: "bg_image", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "text" }
          - label: Philosophy
            name: philosophy
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Content", name: "content", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
          - label: Fun Facts
            name: funfacts
            widget: object
            fields:
              - label: Counters
                name: counter
                widget: list
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
                  - { label: "Count", name: "count", widget: "number" }
      - name: career
        label: Career
        file: content/english/career.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - Label: Open Positions
            name: jobs
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - Label: Requirements
                name: requirements
                widget: list
                fields:
                  - { label: "Requirement", name: "requirement", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      - name: Impressum
        label: Impressum
        file: content/english/legal.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Content", name: "body", widget: "markdown" }
      - name: privacy
        label: Datenschutz
        file: content/english/privacy.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Content", name: "body", widget: "markdown" }
  - name: service
    label: Services
    folder: content/english/service
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: blog
    label: Blog
    folder: content/english/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: navigation
        label: Navigation
        file: data/navigation.yaml
        fields:
          - label: "Main"
            name: "main"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Icon List", name: "iconList", widget: "boolean" }
              - label: "Childs"
                name: "childs"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
          - label: "Footer"
            name: "footer"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }